export const projects = [
  {
    Title: "AI Image Generator",
    Image: "",
    Tools: ["React", "Next.js", "FastAPI", "Modal", "Framer Motion"],
    description: "A high-performance AI-powered image generator with near-instant image synthesis and efficient caching strategies.",
    LiveDemo: "https://dream-gen.vercel.app/",
    VideoDemo: "https://www.youtube.com/watch?v=zNibAnuMcng",
    Github: "https://github.com/ObayM/DreamGen",
  },
  {
    Title: "Customer Churn Predictor",
    Image: "https://cloud-4efdkt0eh-hack-club-bot.vercel.app/01730837711716.jpeg",
    Tools: ["Python", "Machine Learning", "Streamlit", "Gemini API"],
    description: "A machine learning model that predicts customer churn for banks with 85% accuracy, featuring real-time data analysis and AI-driven insights.",
    LiveDemo: "",
    VideoDemo: "",
    Github: "https://github.com/ObayM/Customer-Churn-Predictor",
  },
  {
    Title: "Brain Tumor Classification",
    Image: "",
    Tools: ["Python", "Neural Networks"],
    description: "An AI model that classifies MRI scans into different brain tumor types, providing rapid analysis for neurosurgeons.",
    LiveDemo: "",
    VideoDemo: "https://www.linkedin.com/feed/update/urn:li:activity:7277083768006340609?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7277083768006340609%29&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BaTBJkJ7vQIOOUz7l5CIR3g%3D%3D",
    Github: "https://github.com/ObayM/Brain-Tumor-Classification-",
  },
  {
    Title: "Exoplanets Learning Platform",
    Image: "",
    Tools: ["Next.js", "React", "Framer Motion", "Tailwind CSS"],
    description: "An interactive platform for exploring exoplanets with engaging animations, dynamic content, and a responsive design.",
    LiveDemo: "https://nasa-project-eosin.vercel.app/",
    VideoDemo: "https://www.linkedin.com/posts/obay-dev_were-excited-to-announce-that-weve-completed-activity-7230616601161531392-nAV1?utm_source=share&utm_medium=member_desktop",
    Github: "https://github.com/ObayM/NASA-Project",
  },
  {
    Title: "AI Learning Platform",
    Image: "",
    Tools: ["Next.js", "React", "Firebase", "Clerk", "AI APIs"],
    description: "A personalized AI-powered learning system with interactive roadmaps, flashcards, and progress tracking.",
    LiveDemo: "https://falcon-mind.vercel.app/",
    VideoDemo: "https://www.youtube.com/watch?v=0xljYB3qmqQ",
    Github: "https://github.com/ObayM/FalconMind",
  },
  {
    Title: "AI Flashcards",
    Image: "",
    Tools: ["Next.js", "React", "Firebase", "Clerk", "OpenAI API", "Tailwind CSS"],
    description: "An AI-powered flashcard generator that helps users quickly create and review personalized study materials.",
    LiveDemo: "https://card-crafter.vercel.app/",
    VideoDemo: "https://www.linkedin.com/posts/obay-dev_were-excited-to-announce-that-weve-completed-activity-7230616601161531392-nAV1?utm_source=share&utm_medium=member_desktop",
    Github: "https://github.com/ObayM/CardCrafter",
  },
  {
    Title: "Sports App",
    Image: "",
    Tools: ["Next.js", "React", "Tailwind CSS", "Framer Motion", "Gemini API"],
    description: "A sports-focused web app with an AI-powered meal planner, progress tracker, and interactive quizzes.",
    LiveDemo: "https://sports-era.vercel.app/",
    VideoDemo: "https://www.youtube.com/watch?v=WuQ62QF-Cuk",
    Github: "https://github.com/ObayM/SportsEra",
  },
  {
    Title: "Pantry Tracker",
    Image: "",
    Tools: ["React", "Firebase", "Gemini API", "Tailwind CSS"],
    description: "An AI-driven pantry management tool that tracks inventory and suggests meal plans based on available ingredients.",
    LiveDemo: "https://pantry-tracker-fawn-tau.vercel.app/",
    VideoDemo: "https://www.youtube.com/watch?v=CFQXTCcAmwA",
    Github: "https://github.com/ObayM/Pantry-Tracker",
  },
  {
    Title: "Movie Trends Analyzer",
    Image: "",
    Tools: ["Python", "Pandas", "Matplotlib"],
    description: "A data analysis project that explores trends in the movie industry, using visualizations to uncover key insights.",
    LiveDemo: "",
    VideoDemo: "",
    Github: "https://www.kaggle.com/code/obayprogrammer/tmdb-movies-full-eda",
  },
];


export const awards = [
  {
    Title: "AWS AI & ML Scholarship Recipient",
    Description : "Selected as one of 2,000 recipients worldwide for the AWS AI & ML Scholarship, a full scholarship valued at $4,000 USD, providing access to Udacity’s AI Programming with Python Nanodegree. As one of the youngest recipients at just 16 years old.",
    Images: [
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/01728044770540.jpeg",
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/51718476514709.jpeg",
      "https://media.licdn.com/dms/image/v2/D5622AQHBkA9dsvhMAQ/feedshare-shrink_800/feedshare-shrink_800/0/1728047469562?e=1741219200&v=beta&t=nEDvrOA7z26WMD56jynAPza8Ea0B4_-kR5JWhJfeLY4",
    ],
    AwardingBody: "Amazon Web Services (AWS)",
    Link: "https://www.udacity.com/certificate/e/a492eaf0-2dce-11ef-8db1-5bcf389cf9aa",
    LinkDes: "See Graduation Certificate",
  },
  {
    Title: "Global Nominee @NASA Space apps",
    Description: "Ranked 6th out of 70+ teams and nominated for global judging.",
    Images: [
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/41728665147314.jpeg",
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/11728505003737.jpeg",
      "https://cloud-gc04ootkj-hack-club-bot.vercel.app/0image.png",
    ],
    AwardingBody:"NASA Space apps",
    Link: "https://www.facebook.com/share/p/1HXQP3MPQC/",
    LinkDes: "See Anouncement Post",
  },
  {
    Title: "First Place - Article Competition (Quality Education)",
    Description: "Secured 1st place out of 140 participants internationally in the Student Perspectives and Research Knowledge Articles Competition, under the Quality Education category.",
    Images: [
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/31732315293424.jpeg",
      "https://cloud-6912xb2se-hack-club-bot.vercel.app/2467160767_567546712693789_1580371882457961494_n.jpg",
    ],
    AwardingBody:"STEM Model United Nations (STEM-MUN)",
    Link: "https://www.facebook.com/STEMModelUnitedNations/posts/stem-mun-congratulates-the-top-3-entries-in-each-of-the-two-categories-of-the-sp/567548546026939/",
    LinkDes: "See Anouncement Post",
  },
]
// difsofj